version: '2'
services:
  web: &rails_service_base
    build: .
    command: /usr/local/bin/start.sh
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    container_name: web
  spring:
    <<: *rails_service_base
    command: spring server
    ports: []
    pid: host
    environment:
      SPRING_SOCKET: /tmp/spring/spring.sock
    volumes:
      - .:/myapp
      - spring:/tmp/spring
    container_name: spring
  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 6033:3306 #DB clientからの接続用
    container_name: db

volumes:
  spring:
